name: my_first_pipeline

on:
  push:
    branches:
      - 'master'

jobs:
  built_my_project:
    strategy:
      matrix:
        o_system: [macos-latest, ubuntu-latest]
    runs-on: ${{matrix.o_system}}

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package

      - name: print_if_build_success
        run: echo "Build on ${{matrix.o_system}} finished successfully!!"

      - run: mkdir art && cp target/*.jar art
      - uses: actions/upload-artifact@v3
        with:
          name: build_artefact
          path: art

      - name: print_if_artefact_success
        run: echo "Artefact was upload successfully!!"

  download_artefact:
    needs: built_my_project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: build_artefact
          path: art

      - name: Display structure of downloaded files
        run: ls -l
        working-directory: art

  build:
    name: Build_telegram
    needs: download_artefact
    runs-on: ubuntu-latest
    steps:
      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          document: art/*.jar