name: my_first_pipeline

on:
  push:
    branches:
      - 'master'

jobs:
  built_my_project:
    strategy:
      matrix:
        o_system: [windows-latest, macos-latest, ubuntu-latest]
    runs-on: ${{matrix.o_system}}

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package

      - name: print_if_build_success
        run: echo "Build on ${{matrix.o_system}} finished successfully!!"

      - run: mkdir src/artefacts && cp target/*.jar src/artefacts
      - uses: actions/upload-artifact@v3
        with:
          name: build_artefact
          path: src/artefacts

      - name: print_if_artefact_success
        run: echo "Artefact was upload successfully!!"